language: node_js
node_js: stable
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: HypPKbEZVhAp/PMnRq/dQf98xj3Z7Z7edGbGcLbmZTv1v4RpUkcWa0unTmYG6Z2v5ELFg72TfNQF9SEljJbb3FOILqUNapZAGoEM8+/wr/JnVw7FnGas5V7GHyEeZZbwKTZisZ45CrzMd16fqGM4upg1FKe/ALduy6nn90rns2M=
  on:
    tags: true
    all_branches: true
