language: node_js
node_js: stable
sudo: false
after_success:
- npm run report-coverage
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: UHLmCQ3GGXDljxFVOtG8Xw5/QYf2i8C+818jrDCIFIztpvwUmk+mLZikBz0VWKF08LsyEYP1xGDR8YXGbj2B++fjGa7wRGOXmNRNeRBHR8/0tzQO4FOAYpytwpWxxkbqke0dava90/ZdEqJuYz3lshrZhH9vsGfL4lbESBIIG60=
  on:
    tags: true
    all_branches: true
