language: node_js
node_js:
- '0.10'
deploy:
  provider: npm
  email: d2ltravisdeploy@d2l.com
  api_key:
    secure: S4aVdXHbxvOJyIZiozkT7x0ocTpaRLAOvVXmrQU06FHG6YzgP+fLqBIaKFGziDVMcT6v4KTNpqhBvlhKZNdzNXntYGllGD/7Mw2wObwdZs3J3IPs4N45NAt/jUssPztb8u78DUSf7pshELc08gxx1iu+nAmBcjQrHCRkcMrqBvA=
  on:
    tags: true
    all_branches: true
